version: "3"

services:
    app:
        build: .
        stop_signal: SIGINT
        container_name: market_place
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./:/app
        depends_on:
            - db
        networks:
            - market_place-network

    db:
        image: "postgres:latest"
        container_name: market_place_postgres_db
        restart: always
        env_file:
          - .env
        ports:
            - "5433:5432"
        networks:
            - market_place-network

networks:
  market_place-network: